<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura [
  <!ELEMENT factura (datos-emisor, datos-cliente, detalle-factura)>
  <!ATTLIST factura numero CDATA #REQUIRED fecha CDATA #REQUIRED>

  <!ELEMENT datos-emisor (nombre, cif, telefono)>
  <!ELEMENT datos-cliente (nombre, cif, telefono)>

  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT cif (#PCDATA)>
  <!ELEMENT telefono (#PCDATA)>

  <!ELEMENT detalle-factura (linea+)>
  <!ATTLIST detalle-factura importe CDATA #REQUIRED>

  <!ELEMENT linea (descripcion, cantidad, pvp, oferta?)>
  <!ATTLIST linea codigo-articulo ID #REQUIRED tipo (Libro | DVD | Varios) #REQUIRED>

  <!ELEMENT descripcion (#PCDATA)>
  <!ELEMENT cantidad (#PCDATA)>
  <!ELEMENT pvp (#PCDATA)>
  <!ELEMENT oferta EMPTY>
]>

<factura numero="F1001" fecha="2025-04-01">
  <datos-emisor>
    <nombre>Librería Alfa</nombre>
    <cif>B99887766</cif>
    <telefono>910101010</telefono>
  </datos-emisor>

  <datos-cliente>
    <nombre>Biblioteca Omega</nombre>
    <cif>G11223344</cif>
    <telefono>930303030</telefono>
  </datos-cliente>

  <detalle-factura importe="75.00">
    <linea codigo-articulo="A101" tipo="Libro">
      <descripcion>Cien años de soledad</descripcion>
      <cantidad>1</cantidad>
      <pvp>25.00</pvp>
    </linea>
    <linea codigo-articulo="A102" tipo="DVD">
      <descripcion>Educación ambiental</descripcion>
      <cantidad>1</cantidad>
      <pvp>30.00</pvp>
      <oferta/>
    </linea>
    <linea codigo-articulo="A103" tipo="Varios">
      <descripcion>Bolígrafos</descripcion>
      <cantidad>5</cantidad>
      <pvp>4.00</pvp>
    </linea>
  </detalle-factura>
</factura>

