<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE EquiposNBA [
  <!ELEMENT EquiposNBA (equipo+)>

  <!ELEMENT equipo (nombre, titulos, posicion, quinteto)>
  <!ATTLIST equipo conferencia (este | oeste) #REQUIRED>

  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT titulos (#PCDATA)>
  <!ELEMENT posicion (#PCDATA)>
  <!ELEMENT quinteto (#PCDATA)>
]>

<EquiposNBA>
  <equipo conferencia="oeste">
    <nombre>Los Angeles Lakers</nombre>
    <titulos>17</titulos>
    <posicion>5</posicion>
    <quinteto>LeBron, Davis, Reaves, Russell, Hachimura</quinteto>
  </equipo>

  <equipo conferencia="este">
    <nombre>Boston Celtics</nombre>
    <titulos>

