=== nrcb28/reimagined-palm-tree/panel.dtd
<!ELEMENT panel (vuelo+)>
<!ATTLIST panel 
  aeropuerto CDATA #REQUIRED
  fecha CDATA #REQUIRED>

<!ELEMENT vuelo (origen, destino, hora_salida, hora_llegada)>
<!ATTLIST vuelo 
  codigo ID #REQUIRED
  estado (C | E | R) "E"
  diario (SI | NO) #IMPLIED>

<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>

=== nrcb28/reimagined-palm-tree/panel_vuelos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE panel SYSTEM "panel.dtd">
<panel aeropuerto="JFK" fecha="20/12/2013">
  <vuelo codigo="V22" estado="R" diario="SI">
    <origen>New York</origen>
    <destino>Chicago</destino>
    <hora_salida>9:30</hora_salida>
    <hora_llegada>11:30</hora_llegada>
  </vuelo>

  <vuelo codigo="V23" estado="C" diario="NO">
    <origen>New York</origen>
    <destino>Miami</destino>
    <hora_salida>10:15</hora_salida>
    <hora_llegada>11:15</hora_llegada>
  </vuelo>
</panel>
